---

- name: RabbitMQ | Add rabbitmq.com public key
  become: yes
  apt_key: >
    url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    id=056E8E56

- name: RabbitMQ | Add rabbitmq.com APT Repository
  become: yes
  apt_repository: repo="deb http://www.rabbitmq.com/debian/ testing main"

- name: RabbitMQ | Install
  become: yes
  apt: name=rabbitmq-server state=latest force=yes
  no_log: yes

- name: RabbitMQ | Install plugins
  become: yes
  rabbitmq_plugin: names="{{ item }}"
  with_items: "{{ rabbitmq_plugins }}"
  notify: reload rabbitmq-server
