---

- name: Setup Drupal Redis
  hosts: drupal-redis
  roles:
    - role: dosomething.redis

- name: Setup Drupal WebApp
  hosts: drupal-webapp
  roles:
    - role: dosomething.web
    - role: dosomething.dosomething
