---

- name: Setup Drupal Redis
  hosts: tag_Role_Drupal-Redis
  roles:
    - role: dosomething.redis

- name: Setup Drupal WebApp
  hosts: tag_Role_Drupal-WebApp
  roles:
    - role: dosomething.web
    - role: dosomething.dosomething

# sudo mount -t nfs -o nolock 10.100.20.6:/drupal-static-files /mnt
- name: Mount shared folder to Drupal WebApp
  hosts: tag_Role_Drupal-WebApp
  tasks:
  - name: Install nfs-common
    sudo: yes
    apt: name=nfs-common state=latest
  - name: Ensure mount directory exists
    sudo: yes
    file: >
      path={{ app_shared }}/files
      state=directory
      owner={{ app_user }}
      follow=yes
  - name: Mount NFS
    remote_user: "{{ app_user }}"
    command: mount -t nfs -o nolock 10.100.20.6:/drupal-static-files {{ app_shared }}/files
