---

- name: Setup Drupal Redis
  hosts: tag_Role_Drupal_Redis
  roles:
    - role: dosomething.redis

- name: Setup Drupal WebApp
  hosts: tag_Role_Drupal_WebApp
  roles:
    - role: dosomething.web
    - role: dosomething.phoenix

# sudo mount -t nfs -o nolock 10.100.20.6:/drupal-static-files /mnt
- name: Mount shared folder to Drupal WebApp
  hosts: tag_Role_Drupal_WebApp
  tasks:
  - name: Install nfs-common
    sudo: yes
    apt: name=nfs-common state=latest
  - name: Mount NFS
    sudo: yes
    mount: >
      name=/var/www/www.dosomething.org/shared/files
      src='10.100.20.6:/drupal-static-files'
      fstype=nfs
      opts=nolock
      state=mounted
