---
- src: dosomething.base
- src: dosomething.web
- src: dosomething.search
- src: dosomething.redis
- src: dosomething.dosomething
- src: dosomething.dosomething-dev
- src: dosomething.db
- src: dosomething.vagrant
