---

# PHP
php_ini_settings:
  - section: PHP
    option: upload_max_filesize
    value: 10M
  - section: Date
    option: date.timezone
    value: "{{ timezone }}"

php_fpm_settings:
  - { option: user,   value: "{{ app_user }}" }
  - { option: group,  value: "{{ app_user }}" }
  - { option: listen.backlog,        value: 128 }
  - { option: pm.max_children,       value: 16 }
  - { option: pm.max_spare_servers,  value: 4 }

php_extensions:
  - php5-mysql
  - php5-gd
