---

# App
app_user: dosomething
app_host: staging.beta.dosomething.org
app_root: /var/www/{{ app_host }}/current
app_environment: stage

# Shared
app_create_shared: yes
app_shared: /var/www/{{ app_host }}/shared

# Other
composer_self_update: yes
