---

- name: Install testing utilities using NPM
  npm: name={{ item.name }} version={{ item.version }} global=yes state=latest
  sudo: yes
  with_items:
    - name: mocha-phantomjs
      version: 3.*
    - name: casperjs
      # node 1.2 requires caspser 1.1 branch
      version: 1.1.0-beta3
