---

- name: Install Composer
  become: yes
  shell: >
    curl -sS https://getcomposer.org/installer | php --
    --install-dir={{ composer_path }}
    --filename=composer
  args:
    creates: "{{ composer_path }}/composer"

- name: Update Composer
  become: yes
  shell: composer self-update
  register: composer_update
  changed_when: '"You are already using composer" not in composer_update.stderr'
  when: composer_self_update

- name: Update Composer
  become: yes
  lineinfile:
    create=yes
    dest=/etc/profile.d/composer.sh
    line="export COMPOSER_DISABLE_XDEBUG_WARN=1"
  when: composer_disable_xdebug
