---

- name: Node.js | Adding APT key
  become: yes
  apt_key: >
    url="https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"
    id=68576280

- name: Node.js | Add Repo
  become: yes
  apt_repository: >
    repo="deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

- name: Node.js | Install
  become: yes
  apt: name=nodejs state=latest
