- name: Install Pre-req packages
  become: yes
  apt: name=software-properties-common state=latest

- name: Add HHVM Apt Key
  become: yes
  command: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449

- name: Add HHVM Apt Repo
  become: yes
  apt_repository: repo='deb http://dl.hhvm.com/ubuntu trusty main' state=present

- name: Install HHVM
  become: yes
  apt: name=hhvm state=latest
