- name: Add Jenkins Repo Key
  become: yes
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key

- name: Add Jenkins Repo
  become: yes
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present update_cache=yes

- name: Install Jenkins
  become: yes
  apt: name=jenkins state=latest update_cache=yes

- name: Enable Jenkins on Boot
  become: yes
  service: name=jenkins state=started enabled=yes
