- name: Install Sixpack Apt Prerequisites
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv

- name: Ensures sixpack directories exists
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: dosomething
    group: dosomething
  with_items:
   - /home/dosomething/sixpack

- name: Install Sixpack pip Packages
  pip:
    name: {{ item }}
    virtualenv: /home/dosomething/venv
  with_items:
    - sixpack
    - gunicorn

- name: Install Sixpack configuration dir
  become: yes
  file: path=/etc/sixpack state=directory mode=755 owner=root group=root

- name: Install Sixpack configuration
  become: yes
  template: src=sixpack.yaml.j2 dest=/etc/sixpack/config.yml owner=root group=root mode=644

- name: Configure sixpack gunicorn
  become: yes
  template: src={{ item }} dest=/{{ item }} owner=root group=root mode=644
  with_items:
    - src: etc/systemd/system/gunicorn.socket
      dest: /etc/systemd/system/{{ sixpack_service }}.socket
    - src: etc/systemd/system/gunicorn.service
      dest: /etc/systemd/system/{{ sixpack_service }}.service
    - src: etc/systemd/system/gunicorn.service
      dest: /etc/systemd/system/{{ sixpack_service }}.service

- name: Configure sixpackweb gunicorn
  become: yes
  template: src={{ item.src }} dest=/{{ item.dest }} owner=root group=root mode=644
  vars:
    venv_home: /home/dosomething/venv
    sixpack_service: sixpackweb
    sixpack_service_exec: sixpack.web:start
  with_items:
    - src: etc/systemd/system/gunicorn.socket
      dest: /etc/systemd/system/{{ sixpack_service }}.socket
    - src: etc/systemd/system/gunicorn.service
      dest: /etc/systemd/system/{{ sixpack_service }}.service
    - src: etc/systemd/system/gunicorn.service
      dest: /etc/systemd/system/{{ sixpack_service }}.service

- name: Configure nginx
  become: yes
  template: src={{ item }} dest=/{{ item }} owner=root group=root mode=644
  with_items:
    - etc/nginx/conf.d/sixpack.conf

- name: Enable sixpack sockets
  become: yes
  systemd: name={{ item }} enabled=yes
  with_items:
    - sixpack.socket
    - sixpackweb.socket

- name: Enable sixpack, sixpackweb and nginx
  become: yes
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - sixpack
    - sixpackweb
    - nginx
