- name: Copy HA Proxy Config Into Place
  become: yes
  copy: src=files/ServerConfig/haproxy-prod/haproxy dest=/etc/haproxy/haproxy.cfg onwer=root group=root mode=644 backup=yes
  notify:
    restart haproxy
