- name: Checkout ServerConfig Repo Locally
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Checkout ServerConfig Repo
      git: repo=ssh://git@github.com:DoSomething/ServerConfig.git dest=files/

- name: Copy HA Proxy Config Into Place
  become: yes
  copy: src=files/ServerConfig/haproxy-prod/haproxy dest=/etc/haproxy/haproxy.cfg onwer=root group=root mode=644 backup=yes
  notify:
    restart haproxy

- name: Remove ServerConfig Repo
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Remove ServerConfig Repo Checkout
      file: path=files/ServerConfig state=absent force=yes
