- name: Create ServerConfig Dir
  file: path=/tmp/ServerConfig state=directory owner=root group=root mode=777

- name: Checkout ServerConfig Repo
  git: repo=https://github.com/DoSomething/ServerConfig.git dest=/tmp/ServerConfig

- name: Set File Perms
  become: yes
  file: path=/tmp/ServerConfig/haproxy-prod/haproxy owner=root group=root mode=644

- name: Copy HA Proxy Config Into Place
  become: yes
  command: cp -a /tmp/ServerConfig/haproxy-prod/haproxy dest=/etc/haproxy/haproxy.cfg
  notify:
    restart haproxy

- name: Remove Repo Checkout
  file: path=/tmp/ServerConfig state=absent force=yes
