- name: Copy HA Proxy File Into Place
  become: yes
  copy: content="{{ lookup('file', 'files/haproxy/haproxy') }}" dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=644 backup=yes
  notify: restart haproxy
