---

# App
app_user: dosomething
app_host: international.dosomething.org
app_root: /var/www/{{ app_host }}/current
app_environment: production.international

# Https
app_ssl_enabled: no
app_fastcgi_param_https: "on"

# Redis
redis_bind: 0.0.0.0
redis_port: 6379
