---

# PHP
php_ini_settings:
  - section: PHP
    option: upload_max_filesize
    value: 10M
  - section: Date
    option: date.timezone
    value: "{{ timezone }}"

php_fpm_settings:
  - { option: user,   value: "{{ app_user }}" }
  - { option: group,  value: "{{ app_user }}" }

php_extensions:
  - php7.0-mysql
  - php7.0-gd

php_thirdparty_newrelic: yes
