---

- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo

- name: System | Check current timezone
  remote_user: ubuntu
  shell: cat /etc/timezone
  register: get_timezone
  changed_when: False

- name: System | Set timezone
  remote_user: ubuntu
  become: yes
  command: timedatectl set-timezone {{ timezone }}
  when: '"{{ timezone }}" not in get_timezone.stdout'

- name: System | Ensure locale exists
  remote_user: ubuntu  
  become: yes
  locale_gen: name={{ locale }} state=present

- name: System | Check current locale
  remote_user: ubuntu
  shell: cat /etc/default/locale
  register: get_locale
  changed_when: False

- name: System | Set locale
  remote_user: ubuntu
  become: yes
  command: update-locale LC_ALL={{ locale }} LANG={{ locale }}
  when: '"LC_ALL={{ locale }}" not in get_locale.stdout'

# https://www.percona.com/blog/2014/04/28/oom-relation-vm-swappiness0-new-kernel/
- name: System | Set vm.swappiness
  remote_user: ubuntu
  become: yes
  sysctl: >
    name="vm.swappiness"
    value=1
    sysctl_set=yes
