---

- name: Install Common Tools
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - ntp
    - git
    - curl
    - mailutils
    - tmux
    - screen
    - bind9utils
    - sysstat

- name: Disable AppArmor
  sudo: yes
  apt: name=apparmor state=absent
