---

- name: Install Common Tools
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - ntp
    - git
    - curl
    - mailutils
    - tmux
    - screen
    - bind9utils
    - sysstat
    - ruby
    - ruby-bundler
