---

- name: Create the app user
  sudo: yes
  user: >
    name={{ app_user }}
    password={{ app_user_password }}
    shell=/bin/bash

- name: SSH | Install public keys
  sudo: yes
  authorized_key: >
    user={{ app_user }}
    key="{{ lookup('file', 'files/app_user/ssh/authorized_keys') }}"

- name: SSH | Populate known hosts
  remote_user: "{{ app_user }}"
  copy: >
    src=files/app_user/ssh/known_hosts
    dest=.ssh/known_hosts

- name: Setup sudoers for the app user
  sudo: yes
  template: src=sudoers/app_user.j2 dest=/etc/sudoers.d/{{ app_user }}

- name: Create ~/bin folder to store custom scripts
  remote_user: "{{ app_user }}"
  file: path=bin state=directory

- name: Make custom scripts directory available in $PATH in non-interactive bash
  remote_user: "{{ app_user }}"
  lineinfile: >
    dest=.bashrc
    line="export PATH=$HOME/bin:$PATH"
    insertbefore="# If not running"

- name: Make custom scripts directory available in $PATH
  remote_user: "{{ app_user }}"
  lineinfile: >
    dest=.profile
    line="export PATH=$HOME/bin:$PATH"

# See http://askubuntu.com/questions/247738/why-is-etc-profile-not-invoked-for-non-login-shells
- name: Make /etc/profile.d/* scripts available in non-login bash
  remote_user: "{{ app_user }}"
  lineinfile: >
    dest=.bashrc
    line="source /etc/profile"
    insertbefore="# If not running"
