---

- name: NTP | Check configuration cleanup lock
  sudo: yes
  stat: path=/etc/ntp.conf.lock
  register: ntp_lock

- name: NTP | Cleanup configuration from default servers
  sudo: yes
  lineinfile: >
    dest=/etc/ntp.conf
    regexp=^server
    state=absent
    backup=yes
  when: not ntp_lock.stat.exists
  register: ntp_conf_cleaned

- name: NTP | Lock configuration cleanup
  sudo: yes
  file: path=/etc/ntp.conf.lock state=touch
  when: ntp_conf_cleaned.changed

- name: NTP | Configure provided NTP servers
  sudo: yes
  lineinfile: >
    dest=/etc/ntp.conf
    line="server {{ item }}"
  with_items: ntp_servers
  notify: restart ntp
