- name: Add Nginx Repo Apt Key
  become: yes
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add Nginx Mainline Repo
  become: yes
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=present update_cache=yes

- name: Add Nginx Mainline Source Repo
  become: yes
  apt_repository: repo='deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=present update_cache=yes

- name: Install Nginx
  become: yes
  apt: name=nginx state=latest

- name: Install Nginx Base LB Conf
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=644
  notify: restart nginx

- name: Create DH Param File for PFS TLS Security
  become: yes
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096 creates=/etc/ssl/certs/dhparam.pem

- name: Remove Existing DS Certificate
  become: yes
  file: path=/etc/ssl/certs/ds.org.crt state=absent

- name: Install DS Private Key
  become: yes
  copy: content="{{ ds_priv_key }}" dest=/etc/ssl/certs/ds.org.key owner=root group=root mode=600

- name: Install DS Certificate
  become: yes
  copy: content="{{ ds_cert }}" dest=/etc/ssl/certs/ds.org.crt owner=root group=root mode=600

- name: Copy Intermediate CA
  become: yes
  copy: src=intermediate-ca.crt dest=/tmp/intermediate-ca.crt owner=root group=root mode=664

- name: Append Intermediate CA to Cert
  become: yes
  command: cat /tmp/intermediate-ca.crt >> /etc/ssl/certs/ds.org.crt owner=root group=root mode=600
  notify: restart nginx

- name: Put Sysctl.conf Settings In Place
  become: yes
  sysctl: name={{ item.setting }} value={{ item.value }} sysctl_set=yes reload=yes
  with_items: sysctl_tweaks
  notify: restart nginx

- name: Add Security File Limits
  become: yes
  lineinfile: dest=/etc/security/limits.conf line="{{ item.line }}"
  with_items: limits_tweaks
  notify: restart nginx
