- name: Add Nginx Repo Apt Key
  become: yes
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add Nginx Mainline Repo
  become: yes
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=present update_cache=yes

- name: Add Nginx Mainline Source Repo
  become: yes
  apt_repository: repo='deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=present update_cache=yes

- name: Install Nginx
  become: yes
  apt: name=nginx state=latest

- name: Install Nginx Base LB Conf
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=644
  notify: restart nginx

- name: Create DH Param File for PFS TLS Security
  become: yes
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096 creates=/etc/ssl/certs/dhparam.pem

- name: Lock Down Permission on dhparam file
  become: yes
  file: path=/etc/ssl/certs/dhparam.pem owner=root group=root mode=600

- name: Put Sysctl.conf Settings In Place
  become: yes
  sysctl: name={{ item.setting }} value={{ item.value }} sysctl_set=yes reload=yes
  with_items: sysctl_tweaks
  notify: restart nginx

- name: Add Security File Limits
  become: yes
  lineinfile: dest=/etc/security/limits.conf line="{{ item.line }}"
  with_items: limits_tweaks
  notify: restart nginx

- name: Remove Existing Default Sites Files
  become: yes
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Create ServerConfig Dir
  become: yes
  file: path=/tmp/ServerConfig state=directory owner=root group=root mode=777

- name: Checkout ServerConfig Repo
  git: repo=git@github.com:DoSomething/ServerConfig.git dest=/tmp/ServerConfig accept_hostkey=yes

- name: Set File Perms
  become: yes
  file: path=/tmp/ServerConfig/nginx-prod/nginx-lb.conf owner=root group=root mode=644

- name: Copy Nginx LB Config Into Place
  become: yes
  command: cp -a /tmp/ServerConfig/nginx-prod/nginx-lb.conf /etc/nginx/conf.d/lb.conf
  notify:
    restart nginx

- name: Remove Repo Checkout
  become: yes
  file: path=/tmp/ServerConfig state=absent force=yes
