---

- name: Install Web Server nginx
  apt: name=nginx state=latest
  become: yes

- name: Nginx | Disable default vhost
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
