---

- name: Create setup-www script
  remote_user: "{{ app_user }}"
  template: >
    src=scripts/setup-www.j2
    dest=bin/setup-www
    mode="u=rwx,g=r,o=r"

- name: Setup welcome message
  sudo: yes
  template: >
    src=etc/motd.j2
    dest=/etc/update-motd.d/60-dosomething
    mode="u=rwx,g=rx,o=rx"

- name: Add custom vagrant hosts
  sudo: yes
  lineinfile: >
    dest=/etc/hosts
    line="{{ item }}"
  with_items:
    - "10.0.2.2 northstar.dev"
