---
galaxy_info:
  author: Sergii Tkachenko
  description: DoSomething.org Platform Vagrant Role
  company: DoSomething.org
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
dependencies:
  - { role: "dosomething.base" }
  - { role: "dosomething.db" }
  - { role: "dosomething.redis" }
  - { role: "dosomething.search" }
  - { role: "dosomething.web" }
  - { role: "dosomething.dosomething" }
  - { role: "dosomething.dosomething-dev" }
