---

- name: Ensure app root folder
  file: >
    path={{ app_root }}
    state=directory
    owner={{ app_user }}
    follow=yes
  become: yes

- name: Make app scripts available $PATH
  remote_user: "{{ app_user }}"
  lineinfile: >
    dest=.profile
    line="export PATH={{ app_root }}/bin:$PATH"

- name: Make app scripts available $PATH in non-interactive bash
  remote_user: "{{ app_user }}"
  lineinfile: >
    dest=.bashrc
    line="export PATH={{ app_root }}/bin:$PATH"
    insertbefore="# If not running"
