---

- name: Vhost | Install app vhost configuration file
  sudo: yes
  template: src=nginx/app.j2 dest=/etc/nginx/sites-available/{{ app_user }}
  notify: restart nginx

- name: Vhost | Enable app vhost
  sudo: yes
  file: >
    src=/etc/nginx/sites-available/{{ app_user }}
    dest=/etc/nginx/sites-enabled/{{ app_user }}
    state=link
  notify: restart nginx
