---

- name: Update Java
  sudo: yes
  apt: name=openjdk-7-jdk state=latest

- name: Check if Solr installed
  stat: path=/opt/solr-{{ solr_version }}
  register: solr_dir

- include: solr-first-install.yml
  when: solr_dir.stat.isdir is not defined

- include: solr-install-core.yml

