- name: Create Static Files Directories
  become: yes
  file: path={{ item }} state=directory owner=nginx group=nginx mode=755
  with_items:
    - /var/www/static
    - /var/www/forge

- name: Remove Existing Default Sites Files
  become: yes
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Put Static Site Conf File In Place
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/static.conf
  notify: restart nginx
