- name: Add Nginx Repo Apt Key
  become: yes
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add Nginx Mainline Repo
  become: yes
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=present update_cache=yes

- name: Add Nginx Mainline Source Repo
  become: yes
  apt_repository: repo='deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=present update_cache=yes

- name: Install Nginx
  become: yes
  apt: name=nginx state=latest

- name: Install Nginx Base Conf
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=644
  notify: restart nginx
